import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { pageBySlug, pages, siteUrl } from "../content";
import { JsonLd, SiteFooter, SiteHeader } from "../ui";

export const dynamicParams=false;
export function generateStaticParams(){return pages.map(p=>({slug:p.slug.split('/')}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const p=pageBySlug(slug.join('/'));if(!p)return{};const path=`/${p.slug}/`;return{title:p.title,description:p.description,alternates:{canonical:path},openGraph:{title:`${p.title} | Sephiria Wiki`,description:p.description,url:path,type:"article",images:["/og.webp"]},twitter:{card:"summary_large_image",title:p.title,description:p.description,images:["/og.webp"]}}}
export default async function GuidePage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const page=pageBySlug(slug.join('/'));if(!page)notFound();const parent=page.slug.includes('/')?{name:"Builds",url:"/builds/"}:null;const related=pages.filter(p=>p.slug!==page.slug&&(p.category===page.category||["beginner-guide","builds","boss-guide","progression-guide"].includes(p.slug))).slice(0,3);const schema={"@context":"https://schema.org","@type":page.collection?"CollectionPage":"Article",headline:page.title,description:page.description,url:`${siteUrl}/${page.slug}/`,isPartOf:{"@type":"WebSite",name:"Sephiria Wiki",url:siteUrl},breadcrumb:{"@type":"BreadcrumbList",itemListElement:[{ "@type":"ListItem",position:1,name:"Home",item:siteUrl},...(parent?[{"@type":"ListItem",position:2,name:parent.name,item:`${siteUrl}${parent.url}`}]:[]),{"@type":"ListItem",position:parent?3:2,name:page.title,item:`${siteUrl}/${page.slug}/`} ]}};return <><SiteHeader/><main className="article"><div className="crumbs"><a href="/">Home</a><span>›</span>{parent&&<><a href={parent.url}>{parent.name}</a><span>›</span></>}<b>{page.title}</b></div><section className="article-hero"><div><p className="eyebrow">{page.kicker}</p><h1>{page.title}</h1><p className="dek">{page.description}</p></div><div className="article-mark">{page.title.charAt(0)}</div></section><div className="article-layout"><aside><p>IN THIS GUIDE</p>{page.sections.map((s,i)=><a key={s.heading} href={`#section-${i+1}`}>{String(i+1).padStart(2,'0')} {s.heading}</a>)}</aside><article><p className="lead">{page.intro}</p><figure><img src="/og.webp" alt={`Atmospheric illustration for the ${page.title}`}/><figcaption>Original Sephiria Wiki editorial artwork. No in-game data is represented.</figcaption></figure>{page.sections.map((s,i)=><section id={`section-${i+1}`} key={s.heading}><span>{String(i+1).padStart(2,'0')}</span><h2>{s.heading}</h2><p>{s.body}</p></section>)}<div className="fact-note"><b>Accuracy note</b><p>This launch guide intentionally avoids unverified names, values, effects, and availability claims. Check the current game build and official channels for version-specific facts.</p></div></article></div><section className="related"><p className="eyebrow">KEEP EXPLORING</p><h2>Related guides</h2><div>{related.map(r=><a href={`/${r.slug}/`} key={r.slug}><small>{r.category}</small><b>{r.title}</b><span>→</span></a>)}</div></section></main><SiteFooter/><JsonLd data={schema}/></>}
