// Boss image metadata — auto-generated by export script.
// verified=false means the image needs a human check before it is shown as the boss portrait.
import type { BossAsset } from "./types";

export const bossAssets: Record<string, BossAsset> = {
  "askard.webp": {
    "boss": "askard",
    "asset": null,
    "type": null,
    "source": null,
    "verified": false,
    "note": "No candidate found in sharedassets0 \u2014 needs manual capture."
  },
  "bird-demon.webp": {
    "boss": "bird-demon",
    "asset": "BirdDemon_Idle_00",
    "type": "Texture2D",
    "source": "sharedassets0.assets",
    "verified": true,
    "note": "Name-matched from asset index; visual content not AI-verified."
  },
  "mole-big-bomb.webp": {
    "boss": "mole-big-bomb",
    "asset": "MoleBombBossGround4",
    "type": "Texture2D",
    "source": "sharedassets0.assets",
    "verified": false,
    "note": "Name-matched from asset index; visual content not AI-verified."
  },
  "oink-king.webp": {
    "boss": "oink-king",
    "asset": "OinkBossCallStone_10",
    "type": "Texture2D",
    "source": "sharedassets0.assets",
    "verified": false,
    "note": "Name-matched from asset index; visual content not AI-verified."
  },
  "mad-armadillo.webp": {
    "boss": "mad-armadillo",
    "asset": "BigGolem_Head_Light00",
    "type": "Texture2D",
    "source": "sharedassets0.assets",
    "verified": false,
    "note": "Name-matched from asset index; visual content not AI-verified."
  },
  "larid.webp": {
    "boss": "larid",
    "asset": null,
    "type": null,
    "source": null,
    "verified": false,
    "note": "No candidate found in sharedassets0 \u2014 needs manual capture."
  }
};
